name: deeply
description: Update nested maps with keyPath and callback.
version: 1.1.0
homepage: https://github.com/fosscom/deeply

environment:
    sdk: '>=2.8.1 <3.0.0'



dev_dependencies:
  test: any
  pedantic: ^1.9.0